server:
  port: 8082
spring:
  application:
    name: financier-app
  datasource:
    url: jdbc:postgresql://ec2-18-214-238-28.compute-1.amazonaws.com:5432/d5r6njfc2ebg97
    username: imtsmvppttiytq
    password: 56a4a1b67ca21eef335958edce8cff2ef8612d56193f50247a376ac9b9309319

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-for-money-turn.herokuapp.com/eureka

