server:
  port: 8082
spring:
  application:
    name: financier-app
  datasource:
    url: jdbc:postgresql://
  ec2-44-193-228-249.compute-1.amazonaws.com:5432/d2fi4bula7befv
    username:
  fuyrsqxatrpwkp
    password: aea94a926c313f4c38cb64bb5afa619feab529948a8534f9d575aa6c7b2e278e


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-for-money-turn.herokuapp.com/eureka

