server:
  port: 8082
spring:
  application:
    name: financier-app
  datasource:
    url:  jdbc:postgresql://localhost:5432/financier
    username: juniper
    password: 112233


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka

